language: node_js
node_js:
  - "12"
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGPORT=5432
    - DB_NAME=travelsare
    - DB_USER=postgres
    - DB_PASSWORD=postgres
before_script:
  - psql --command="CREATE DATABASE travelshare;"
install:
  - npm install
jobs:
  include:
    - stage: test
      script:
        - npm run test
