language: node_js
node_js:
  - "12"
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGPORT=5433
    - DB_NAME=travelshare
    - DB_USER=postgres
    - DB_PASSWORD=postgres
    - PGDATA="/var/lib/postgresql/data"

before_script:
  # - addgroup -S postgres && adduser -S postgres -G postgres || true
  # - sudo mkdir -p /var/lib/postgresql/data
  - psql -c 'create database travelshare;'
  # - sudo chown -R postgres:postgres /var/lib/postgresql/data
install:
  - npm install
jobs:
  include:
    - stage: test
      script:
        # - initdb
        # - pg_ctl start
        # - psql -c 'create database travelshare;'
        - npm run test
