language: node_js
node_js:
  - "12"
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGPORT=5433
before_script:
  - psql -c "ALTER USER postgres WITH ENCRYPTED PASSWORD 'postgres';"
  - psql -c 'create database travelshare;'
install:
  - npm install --force
jobs:
  include:
    - stage: test
      script:
        - npm run test_dev
