language: node_js
node_js:
  - "12"
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGPORT=5432
    - DB_NAME=travelsare
    - DB_USER=postgres
    - DB_PASSWORD=postgres
    - PGDATA="/var/lib/postgresql/data"

before_script:
  - sudo mkdir -p /var/lib/postgresql/data
  - sudo chown -R postgres:postgres /var/lib/postgresql/data
  - sudo chmod -R 777 /var/lib/postgresql/data
  - initdb
  - pg_ctl start
  - psql --command="CREATE DATABASE travelshare;"
install:
  - npm install
jobs:
  include:
    - stage: test
      script:
        - npm run test
