language: node_js
node_js:
  - "12"
services:
  - postgresql
addons:
  postgresql: "14"
  apt:
    packages:
      - postgresql-14
      - postgresql-client-14
env:
  global:
    - PGPORT=5432
    - DB_NAME=travelsare
    - DB_USER=postgres
    - DB_PASSWORD=postgres
    - PGDATA="/var/lib/postgresql/data"

# before_script:
#   - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
#   - sudo service postgresql restart
#   - sleep 1
#   - postgres --version
script:
  - psql -c 'create database travelshare;' -U postgres
install:
  - npm install
jobs:
  include:
    - stage: test
      script:
        - npm run test
