language: node_js
services:
  - postgresql
env:
  global:
    - PGPORT=5432
    - DB_NAME=travelshare
    - DB_USER=postgres
    - DB_PASSWORD=postgres
before_script:
  - psql -c 'create database travelshare;' -U postgres
install:
  - npm install
cache:
  directories:
    - "node_modules"
