version: "3.8"
services:
  db_test:
    image: postgres
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: travelshare
    volumes:
      - /var/lib/postgresql/data_test
    ports:
      - "5432:5432"
  rest:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app/test
      - /app/node_modules
    depends_on:
      - db_test
