name: tests

on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          DATABASE_HOST: 127.0.0.1
          POSTGRES_USER: postgres
          POSTGRES_DB: travelshare
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Connect to PostgreSQL
        run: /bin/bash script.sh  
      -name : Test
        run: npm run test
